### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by connorshea** [connorshea/VideoGameList#734]
```
Randomized with seed 47487
                                                                                                                                    
  1) Event User Relationship Event Destructions Event should be deleted when Relationship is deleted
     Failure/Error: let(:relationship_followed) { create(:relationship, followed: user) }
     
     ActiveRecord::RecordInvalid:
       Validation failed: Follower has already been taken
     # ./spec/models/event_spec.rb:118:in `block (3 levels) in <top (required)>'
     # ./spec/models/event_spec.rb:131:in `block (3 levels) in <top (required)>'
```

**Comment by connorshea** [comment]
This was fixed in #755.
